apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.8/manifests/install.yaml

# - clusters-secrets.yaml
# - repos-secrets.yaml

# changes to config maps
# patchesStrategicMerge:
# - overlays/argo-cd-cm.yaml
