apiVersion: v1
# not really a secret, since this repository is public
kind: Secret
metadata:
  name: ehakan-cluster-speedrun
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/ehakan/cluster-speedrun
